development:
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: new_restaurant_app_development
  username: postgres
  password: postgres

production:
  database: <%= ENV["DATABASE_URL"]%>